### PR TITLE
Test new openfe & gufe rc

### PR DESCRIPTION
**Pull request by mikemhenry**

### CODE REVIEW

**Comment by mikemhenry** [comment]
```
self = <[AttributeError("'DummyProtocol' object has no attribute '_settings'") raised in repr()] DummyProtocol object at 0x7f125c289e70>
settings = {':is_custom:': True, '__class__': 'DummySpecificSettings', '__module__': 'gufe.tests.test_protocol', 'forcefield_sett..._class__': 'OpenMMSystemGeneratorFFSettings', '__module__': 'gufe.settings.models', 'constraints': 'hbonds', ...}, ...}

    def __init__(self, settings: Settings):
        """
        Parameters
        ----------
        settings : Settings
          The parameters for this particular method.  This will be a specialised
          subclass for this particular Protocol.
    
        Note
        ----
        Once the Protocol object is created, the input Settings are frozen,
        so should be finalised before creating the Protocol instance.
        """
>       self._settings = settings.frozen_copy()
E       AttributeError: 'dict' object has no attribute 'frozen_copy'
```

Hmmm, getting an error in the gufe internals...

@richardjgowers I can look into this but if you want to take just a minute to skim the errors that would be great!

**Comment by richardjgowers** [comment]
@mikemhenry it's this PR: https://github.com/OpenFreeEnergy/gufe/pull/169/files

The settings variable there needs to be a `Settings` subclass, not a dict

**Comment by mikemhenry** [comment]
Yse I saw that but it looks like alchemiscale is importing the dummy protocol from gufe `from gufe.tests.test_protocol import DummyProtocol` and then getting the default settings from it `protocol=DummyProtocol(settings=DummyProtocol.default_settings())` so it should be the right object, but I will dig to see where it is getting cast into a dict

**Comment by mikemhenry** [comment]
`self = <[AttributeError("'DummyProtocol' object has no attribute '_settings'") raised in repr()] DummyProtocol object at 0x7f1d05f33190>` probably just need to check the changes in `DummyProtocol`

**Comment by mikemhenry** [comment]
Okay so the actual problem is that the settings object is not getting parsed back into a gufe object, this is the bit https://github.com/OpenFreeEnergy/gufe/blob/main/gufe/tokenization.py#L66 where we re-create the object, but instead of a settings object, we have a serialized settings dictionary: 

```
cls= <class 'gufe.tests.test_protocol.DummyProtocol'> 
args= () 
kwargs= {
    "settings": {
        "__class__": "DummySpecificSettings",
        "__module__": "gufe.tests.test_protocol",
        ":is_custom:": True,
        "forcefield_settings": {
            "__class__": "OpenMMSystemGeneratorFFSettings",
            "__module__": "gufe.settings.models",
            ":is_custom:": True,
            "constraints": "hbonds",
            "rigid_water": True,
            "hydrogen_mass": 3.0,
            "forcefields": [
                "amber/ff14SB.xml",
                "amber/tip3p_standard.xml",
                "amber/tip3p_HFE_multivalent.xml",
                "amber/phosaa10.xml",
            ],
            "small_molecule_forcefield": "openff-2.0.0",
            "nonbonded_cutoff": {
                "magnitude": 1.0,
                "unit": "nanometer",
                ":is_custom:": True,
                "pint_unit_registry": "openff_units",
            },
            "nonbonded_method": "PME",
        },
        "thermo_settings": {
            "__class__": "ThermoSettings",
            "__module__": "gufe.settings.models",
            ":is_custom:": True,
            "temperature": {
                "magnitude": 298.0,
                "unit": "kelvin",
                ":is_custom:": True,
                "pint_unit_registry": "openff_units",
            },
            "pressure": None,
            "ph": None,
            "redox_potential": None,
        },
        "n_repeats": 21,
    }
}
```

You can see the difference in what the `SmallMoleculeComponent` looks like here:

```
cls= <class 'gufe.components.smallmoleculecomponent.SmallMoleculeComponent'> 
args= () 
kwargs= {'rdkit': <rdkit.Chem.rdchem.Mol object at 0x73aeb48518c0>}
```

**Comment by mikemhenry** [comment]
This is what is getting "sent" to GUFE:
```
[
    "DummyProtocol-140583b69a04f875265977f9e5f114d8",
    {
        "settings": {
            "__class__": "DummySpecificSettings",
            "__module__": "gufe.tests.test_protocol",
            ":is_custom:": true,
            "forcefield_settings": {
                "__class__": "OpenMMSystemGeneratorFFSettings",
                "__module__": "gufe.settings.models",
                ":is_custom:": true,
                "constraints": "hbonds",
                "rigid_water": true,
                "hydrogen_mass": 3.0,
                "forcefields": [
                    "amber/ff14SB.xml",
                    "amber/tip3p_standard.xml",
                    "amber/tip3p_HFE_multivalent.xml",
                    "amber/phosaa10.xml",
                ],
                "small_molecule_forcefield": "openff-2.0.0",
                "nonbonded_cutoff": {
                    "magnitude": 1.0,
                    "unit": "nanometer",
                    ":is_custom:": true,
                    "pint_unit_registry": "openff_units",
                },
                "nonbonded_method": "PME",
            },
            "thermo_settings": {
                "__class__": "ThermoSettings",
                "__module__": "gufe.settings.models",
                ":is_custom:": true,
                "temperature": {
                    "magnitude": 298.0,
                    "unit": "kelvin",
                    ":is_custom:": true,
                    "pint_unit_registry": "openff_units",
                },
                "pressure": null,
                "ph": null,
                "redox_potential": null,
            },
            "n_repeats": 21,
        },
        "__qualname__": "DummyProtocol",
        "__module__": "gufe.tests.test_protocol",
        ":version:": 1,
    },
]
```

**Comment by mikemhenry** [comment]
@dotsdl @ianmkenney Could I get you guys to take a look at this? I think the issue might be here: https://github.com/openforcefield/alchemiscale/blob/main/alchemiscale/keyedchain.py 
Settings isn't a gufe tokenizable, so I think that might be where the breakdown is in this encode/decode loop

**Comment by dotsdl** [comment]
@ianmkenney and I are looking into these failures now @mikemhenry, @richardjgowers; the good news is that I think we encountered something like this before, so will report back once we've characterized it further.

**Comment by dotsdl** [comment]
Think I may have fixed the problem you encountered @mikemhenry; see notes in 328aa66.

**Comment by mikemhenry** [comment]
Awesome! I see how that used to work just fine by accident as well :upside_down_face:

**Comment by dotsdl** [comment]
@ianmkenney will lead the charge here on getting `openfe` and `gufe` 1.0 through QA on alchemiscale.org. Thanks @mikemhenry for getting us started here!

**Comment by dotsdl** [comment]
Reviewing this next!

**Review by dotsdl — APPROVED** [review]
This is finally ready to go! Thanks @mikemhenry and @ianmkenney for your work on this!

**Pull request merged**
