### PR TITLE
Rename package internals  v2

### PR DESCRIPTION
**Pull request by hmacdope**
Fixes https://github.com/openforcefield/alchemiscale/issues/72 https://github.com/openforcefield/alchemiscale/issues/73

Renames all the package internals and docs to alchemiscale rather than fah-alchemy.

@dotsdl I don't want to put obstacles in your way for https://github.com/openforcefield/alchemiscale/pull/56 so perhaps we will wait for that to come in and then merge? Up to you. 😄

TODOs

 - [X] Check docker compose still works, from what I can see is all good?

### CODE REVIEW

**Comment by hmacdope** [comment]
@mikemhenry  Might continue here seeing as I couldn't get the docker CI to build off my fork PR.

**Comment by hmacdope** [comment]
From what I can tell the `docker-compose` spin up seems to work. I wasn't quite sure how to run the `client._api_check` from the spun up containers but the CLI seems to behave. Not quite sure what I need to change to get codecov to work again but I will have a look.

**Comment by hmacdope** [comment]
@dotsdl and I have decided to not hold for #56 and instead will push to merge and #56 can catch up.

**Review by dotsdl — APPROVED** [review]
Thank you so much @hmacdope for hitting all of these! Looks good to merge! I'll handle the conflicts and merge it.

**Pull request merged**
