### PR TITLE
Adding perses, other production deps to docker packaging

### PR DESCRIPTION
**Pull request by dotsdl**

### CODE REVIEW

**Comment by dotsdl** [comment]
@mikemhenry could I get your blessing on this one? Also, are there opportunities on the `perses` side to reduce some of its hard dependencies with more lazy imports?

**Review by hmacdope — APPROVED** [review]

**Comment by mikemhenry** [comment]
@dotsdl chatted on slack, the plan is to have perses as a dep (from conda-forge) the do a pip install on top (plus deps missing from our 0.10.1 recipe) and see if that works

**Comment by dotsdl** [comment]
Getting fun errors like:
```
docker-alchemiscale-client-API-1   | [2023-03-14 05:12:10 +0000] [56] [ERROR] Exception in ASGI application
docker-alchemiscale-client-API-1   | Traceback (most recent call last):
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
docker-alchemiscale-client-API-1   |     result = await app(  # type: ignore[func-returns-value]
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
docker-alchemiscale-client-API-1   |     return await self.app(scope, receive, send)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/fastapi/applications.py", line 273, in __call__
docker-alchemiscale-client-API-1   |     await super().__call__(scope, receive, send)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/starlette/applications.py", line 120, in __call__
docker-alchemiscale-client-API-1   |     await self.middleware_stack(scope, receive, send)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
docker-alchemiscale-client-API-1   |     raise exc
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
docker-alchemiscale-client-API-1   |     await self.app(scope, receive, _send)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
docker-alchemiscale-client-API-1   |     raise exc
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
docker-alchemiscale-client-API-1   |     await self.app(scope, receive, sender)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
docker-alchemiscale-client-API-1   |     raise e
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
docker-alchemiscale-client-API-1   |     await self.app(scope, receive, send)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/starlette/routing.py", line 716, in __call__
docker-alchemiscale-client-API-1   |     await route.handle(scope, receive, send)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
docker-alchemiscale-client-API-1   |     await self.app(scope, receive, send)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
docker-alchemiscale-client-API-1   |     response = await func(request)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
docker-alchemiscale-client-API-1   |     raw_response = await run_endpoint_function(
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
docker-alchemiscale-client-API-1   |     return await run_in_threadpool(dependant.call, **values)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
docker-alchemiscale-client-API-1   |     return await anyio.to_thread.run_sync(func, *args)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
docker-alchemiscale-client-API-1   |     return await get_asynclib().run_sync_in_worker_thread(
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
docker-alchemiscale-client-API-1   |     return await future
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
docker-alchemiscale-client-API-1   |     result = context.run(func, *args)
docker-alchemiscale-client-API-1   |   File "/tmp/alchemiscale/interface/api.py", line 156, in create_network
docker-alchemiscale-client-API-1   |     an = AlchemicalNetwork.from_dict(network)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/gufe/tokenization.py", line 261, in from_dict
docker-alchemiscale-client-API-1   |     return dict_decode_dependencies(dct)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/gufe/tokenization.py", line 518, in dict_decode_dependencies
docker-alchemiscale-client-API-1   |     modify_dependencies(dct, from_dict, is_gufe_dict, mode='decode', top=True)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/gufe/tokenization.py", line 450, in modify_dependencies
docker-alchemiscale-client-API-1   |     obj = {key: modify_dependencies(value, modifier, is_mine, mode=mode, top=False)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/gufe/tokenization.py", line 450, in <dictcomp>
docker-alchemiscale-client-API-1   |     obj = {key: modify_dependencies(value, modifier, is_mine, mode=mode, top=False)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/gufe/tokenization.py", line 454, in modify_dependencies
docker-alchemiscale-client-API-1   |     obj = [modify_dependencies(item, modifier, is_mine, mode=mode, top=False)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/gufe/tokenization.py", line 454, in <listcomp>
docker-alchemiscale-client-API-1   |     obj = [modify_dependencies(item, modifier, is_mine, mode=mode, top=False)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/gufe/tokenization.py", line 450, in modify_dependencies
docker-alchemiscale-client-API-1   |     obj = {key: modify_dependencies(value, modifier, is_mine, mode=mode, top=False)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/gufe/tokenization.py", line 450, in <dictcomp>
docker-alchemiscale-client-API-1   |     obj = {key: modify_dependencies(value, modifier, is_mine, mode=mode, top=False)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/gufe/tokenization.py", line 450, in modify_dependencies
docker-alchemiscale-client-API-1   |     obj = {key: modify_dependencies(value, modifier, is_mine, mode=mode, top=False)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/gufe/tokenization.py", line 450, in <dictcomp>
docker-alchemiscale-client-API-1   |     obj = {key: modify_dependencies(value, modifier, is_mine, mode=mode, top=False)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/gufe/tokenization.py", line 458, in modify_dependencies
docker-alchemiscale-client-API-1   |     obj = modifier(obj)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/gufe/tokenization.py", line 492, in from_dict
docker-alchemiscale-client-API-1   |     obj = _from_dict(dct)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/gufe/tokenization.py", line 513, in _from_dict
docker-alchemiscale-client-API-1   |     return cls._from_dict(dct)
docker-alchemiscale-client-API-1   |   File "/opt/conda/lib/python3.9/site-packages/gufe/components/smallmoleculecomponent.py", line 244, in _from_dict
docker-alchemiscale-client-API-1   |     a.SetIsotope(atom[1])
docker-alchemiscale-client-API-1   | Boost.Python.ArgumentError: Python argument types in
docker-alchemiscale-client-API-1   |     Atom.SetIsotope(Atom, str)
docker-alchemiscale-client-API-1   | did not match C++ signature:
docker-alchemiscale-client-API-1   |     SetIsotope(RDKit::Atom {lvalue}, unsigned int)
```
on our test instance when adding an `AlchemicalNetwork` via the client. Wasn't seeing these before; unclear how our change of approach is leading to this, unless there's some weird mangling of `rdkit` also happening here.

**Comment by mikemhenry** [comment]
Oh that is gross

**Pull request merged**
