### PR TITLE
Changes in line with `gufe`#148

### PR DESCRIPTION
**Pull request by dotsdl**
Changes in line with `gufe`#148.

### CODE REVIEW

**Comment by dotsdl** [comment]
Do not merge until OpenFreeEnergy/gufe#148 is merged.

**Comment by mikemhenry** [comment]
@dotsdl is the expectation that this should work with `gufe@main` or just `gufe@alchemiscale-compute`

**Comment by dotsdl** [comment]
`gufe@main` now that gufe#148 is merged.

**Review by hmacdope — APPROVED** [review]
LGTM, merge when ready.

**Comment by hmacdope** [comment]
Ah wait you will still have to update `devtools` conda envs, but feel free to do that then merge.

**Review by mikemhenry — CHANGES_REQUESTED** [review]
Just need to update the conda env for the tests to make sure this works on gufe@main (you don't need to wait for my re-review once this is done)

**Comment by dotsdl** [comment]
@mikemhenry do we still need `git+https://github.com/mikemhenry/openff-models.git@support_nested_models` anywhere in the stack? I don't remember why I needed to add this at one point, but not sure if it's needed anymore?

**Comment by dotsdl** [comment]
@mikemhenry any insights into the CI failures? Looks like `openfe` use of `openmmtools` might be biting us with `numba`?

**Comment by dotsdl** [comment]
I'm not seeing this issue locally on a fresh env built from the same env file we're using for CI here.

**Comment by dotsdl** [comment]
Pinned `numpy<1.24` per https://github.com/numba/numba/issues/8615#issuecomment-1360792615

Thanks @hmacdope for finding this! Looks like CI is proceeding now.

**Pull request merged**
