### PR TITLE
Set pydantic version less than 2.0 for all conda envs

### PR DESCRIPTION
**Pull request by dotsdl**
Pydantic 2.0 comes with major changes that we are not yet ready to support, and installs of it in environments that use `alchemiscale` are likely to break usage. This PR sets the version spec to <2.0 for pydantic in all conda envs.

### CODE REVIEW

**Comment by hmacdope** [comment]
Just FYI if you want to support pydantic~1 schema from pydantic>=2.0.0a @mattwthompson, @jhorton and I have been using this to import the v1 api from v2. 

```python
    from pydantic.v1 import BaseModel, Field
```

You can then use the following guard to support both versions.

```python
try:
    from pydantic.v1 import BaseModel, Field
except ImportError:
    from pydantic import BaseModel, Field
```

**Comment by dotsdl** [comment]
Oh gotcha, I suppose that would be the preferred approach to avoid holding back the rest of the stack?

**Comment by dotsdl** [comment]
Trying out the import guard approach; will see if this breaks our tests.

**Comment by dotsdl** [comment]
Reverting to just supporting `pydantic < 2.0` for now. We'll work toward proper `pydantic` 2.0 support in a future PR; tests gave an opaque error when we tried doing the import guard approach above: https://github.com/openforcefield/alchemiscale/actions/runs/5791301527/job/15695900360?pr=160

**Pull request merged**
