### PR TITLE
Add deplyoment docs v2

### PR DESCRIPTION
**Pull request by mikemhenry**

### CODE REVIEW

**Comment by mikemhenry** [comment]
This is ready for a review, let me know what changes you would like to see!

**Review by dotsdl — APPROVED** [review]
Thanks for doing this @mikemhenry! I've sculpted and expanded things a bit. Please merge if satisfied!

**Comment by mikemhenry** [comment]
Awesome! I will fix the build warnings we get, also I like to have each sentence on its own line since it doesn't affect the way it renders but makes the diff easier so if you don't have any objections I will fix those

**Comment by dotsdl** [comment]
> Awesome! I will fix the build warnings we get, also I like to have each sentence on its own line since it doesn't affect the way it renders but makes the diff easier so if you don't have any objections I will fix those

Oh yeah, apologies I usually write that way as well for the same reason; I may have failed to newline in some instances.

**Comment by mikemhenry** [comment]
I just saw one instance of it in the diff so really no worries!

**Comment by mikemhenry** [comment]
You can view the docs here https://alchemiscale--157.org.readthedocs.build/en/157/

**Comment by mikemhenry** [comment]
Looks good now, but there are a few tips from #113 that I want to make sure make it in before we give this another review.

**Comment by dotsdl** [comment]
Reviewing! Thanks @mikemhenry!

**Comment by mikemhenry** [comment]
> Docs - build and deploy Expected — Waiting for status to be reported 

Do you want me to update the branch protection settings to fix this?

**Comment by dotsdl** [comment]
@mikemhenry yes please! Sorry for the delay here!

**Comment by mikemhenry** [comment]
@dotsdl fixed the checks! The web ui is being weird so I couldn't add any checks other than the tests but after this gets merged I will see if I can make the RTD build, black, and python 3.11 required as well

**Review by dotsdl — APPROVED** [review]
Looks fantastic @mikemhenry! Thank you for all your hard work on this. Merging!

**Pull request merged**
