### PR TITLE
release 0.5.0 prep

### PR DESCRIPTION
**Pull request by dotsdl**
- **Update prod envs to use Python 3.11**
- **Update all envs to use gufe 1.0.0, openfe 1.0.1**

### CODE REVIEW

**Comment by mikemhenry** [comment]
Don't forget to add `curl` to the env

**Comment by dotsdl** [comment]
Seeing no issues with Python 3.12 use in my testing. @mikemhenry, @IAlibay, @j-wags can you remind me what reservations we had for using it?

**Comment by IAlibay** [comment]
I think it was ambertools / openmmforcefields but that's fixed now. At least OpenFE runs CI on 3.12 just fine. 

Only dependency I'm not sure about is oechem, since we don't use it that much in our tests.

**Comment by dotsdl** [comment]
Okay cool, this is great news! I think we can proceed with Python 3.12 and see if we actually hit any issues from users.

**Pull request merged**
