### PR TITLE
Simplify `action_tasks`

### PR DESCRIPTION
**Pull request by ianmkenney**
`action_tasks` previously issued queries for each task to be actioned. This PR reduces this to a single query using the `UNWIND` clause, while accounting for the potential order loss from the `UNWIND`. Local tests show equal to improved performance depending on the number of tasks actioned. For $n=1$ tasks, the performance remains unchanged (~0.3 s). For $n=10, 100, 1000$, however, the runtime is reduced by (very) roughly $50\\%$, $80\\%$, and $90\\%$, respectively. More concretely this comes out to around:

* $n=10$; $0.7$ s to  $0.4$ s
* $n=100$; $3$ s to $0.6$ s
* $n=1000$; $24$ s to $1.6$ s

### CODE REVIEW

**Comment by dotsdl** [comment]
Awesome work @ianmkenney! Is this ready for review?

**Comment by ianmkenney** [comment]
@dotsdl Will request review after merging #244 and resolving the ensuing conflicts

**Comment by ianmkenney** [comment]
@dotsdl should be good for review

**Review by dotsdl — APPROVED** [review]
Looks excellent @ianmkenney! Merge when satisfied!

**Pull request merged**
